spring:
  application:
    name: FitnessClub

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

app:
  i18n:
    basename: classpath:i18n/messages/messages,classpath:i18n/errors/errors,classpath:i18n/validations/validations
    encoding: UTF-8
    fallback-to-system-locale: false
    cache-seconds: 0
  security:
    cookie:
      secure: false
      max-age: ${REFRESH_TTL}
      same-site: Lax
      cookie-name: refresh_token
      path: /api/auth/refresh
    jwt:
      secret: ${JWT_SECRET}
      access-token-expiration: 15m
    config:
      b-crypt-strength: 12
      password-encoder: argon2
    session:
      max-sessions: 5
    refresh:
      ttl: ${REFRESH_TTL}
      pepper: ${REFRESH_PEPPER}
      length: 64